clone_folder: "c:\\WORK"
clone_depth: 5

skip_branch_with_pr: true

platform:
  - x64

environment:
  global:
    CABOPTS:  --store-dir=C:\\SR --http-transport=plain-http
    CHOCOCMD: ghc --version %GHCVER%
  matrix:
    - GHCVER: 8.8.1
    - GHCVER: 8.6.5

cache:
  - dist-newstyle
  - "c:\\sr -> appveyor.yml"

for:
  -
    matrix:
      only:
        - platform: x86
    environment:
      global:
        GHCOPTS: --forcex86

install:
 - choco source add -n mistuke -s https://www.myget.org/F/mistuke/api/v2
 - choco install %CHOCOCMD% -y %GHCOPTS% %CHOCOPTS% --ignore-dependencies
 - choco install -y cabal %CHOCOPTS%
 - refreshenv

before_build:
 - cabal --version
 - ghc --version
 - cabal %CABOPTS% v2-update

build_script:
 - cabal %CABOPTS% v2-build -j all --max-backjumps=-1